module.exports = {
	location: 'ho chi minh, district 2',
	types: {
		airport: -3,
		art_gallery: 4,
		atm: 1,
		bakery: 3,
		bank: 1,
		bar: 2,
		bicycle_store: 2,
		book_store: 3,
		bus_station: 1,
		cafe: 9,
		campground: -1,
		car_dealer: -1,
		car_rental: -1,
		car_repair: -2,
		car_wash: -2,
		cemetery: 2,
		church: 1,
		embassy: 2,
		furniture_store: -1,
		gas_station: -3,
		gym: 1,
		laundry: 1,
		library: 2,
		liquor_store: 1,
		lodging: 2,
		museum: 4,
		night_club: 2,
		park: 4,
		parking: 1,
		pharmacy: 1,
		restaurant: 5,
		rv_park: -1,
		school: 1,
		stadium: -1,
		storage: -1,
		store: 2,
		subway_station: 5,
		taxi_stand: 2,
		train_station: 6,
		transit_station: 7,
		university: 8
	}
}
